import type {
  ContractorProfile,
  Opportunity,
  PastAward,
  SavedSearch,
  DashboardMetrics,
  Note,
} from "./types";

// ---------------------------------------------------------------------------
// Contractors
// ---------------------------------------------------------------------------

export const contractors: ContractorProfile[] = [
  {
    id: "c1",
    name: "Northbridge Defense Systems",
    cage_code: "5M8K2",
    duns: "078432156",
    naics_codes: ["541511", "541512", "541519"],
    capabilities: [
      "Cybersecurity Operations",
      "Threat Intelligence",
      "Secure Software Development",
      "Zero Trust Architecture",
    ],
    agencies_worked_with: ["DoD", "Army", "DHS"],
    location: "Arlington, VA",
    website: "https://northbridgedefense.com",
    employee_count: 4200,
    annual_revenue: "$680M",
    past_award_count: 47,
    past_award_value: "$1.2B",
    is_prime: true,
    teaming_fit_score: 94,
    contact_name: "Rebecca Thornton",
    contact_email: "r.thornton@northbridgedefense.com",
    contact_phone: "(703) 555-0142",
    tags: ["Active Partner", "Top Performer"],
    created_at: "2024-06-15T10:00:00Z",
  },
  {
    id: "c2",
    name: "Meridian Federal Solutions",
    cage_code: "3R7J9",
    duns: "143287605",
    naics_codes: ["541611", "541613", "541690"],
    capabilities: [
      "Management Consulting",
      "Program Management",
      "Organizational Transformation",
      "Acquisition Support",
    ],
    agencies_worked_with: ["GSA", "VA", "HHS"],
    location: "Bethesda, MD",
    website: "https://meridianfederal.com",
    employee_count: 1800,
    annual_revenue: "$310M",
    past_award_count: 32,
    past_award_value: "$540M",
    is_prime: true,
    teaming_fit_score: 87,
    contact_name: "Daniel Okafor",
    contact_email: "d.okafor@meridianfederal.com",
    contact_phone: "(301) 555-0278",
    tags: ["Active Partner"],
    created_at: "2024-07-22T14:30:00Z",
  },
  {
    id: "c3",
    name: "Apex Cyber Group",
    cage_code: "8N4P1",
    duns: "265918374",
    naics_codes: ["541512", "541519"],
    capabilities: [
      "Penetration Testing",
      "Incident Response",
      "Security Operations Center",
      "Cloud Security",
    ],
    agencies_worked_with: ["DoD", "DHS", "Air Force"],
    location: "San Antonio, TX",
    website: "https://apexcybergroup.com",
    employee_count: 950,
    annual_revenue: "$145M",
    past_award_count: 19,
    past_award_value: "$230M",
    is_prime: true,
    teaming_fit_score: 91,
    contact_name: "Maria Santos",
    contact_email: "m.santos@apexcyber.com",
    contact_phone: "(210) 555-0394",
    tags: ["Top Performer", "Preferred Vendor"],
    created_at: "2024-08-10T09:15:00Z",
  },
  {
    id: "c4",
    name: "Summit Analytics Corp",
    cage_code: "2K6L8",
    duns: "387041529",
    naics_codes: ["541511", "541519", "541690"],
    capabilities: [
      "Data Analytics",
      "Machine Learning",
      "Business Intelligence",
      "Data Engineering",
    ],
    agencies_worked_with: ["DoD", "Army", "DOE"],
    location: "Reston, VA",
    website: "https://summitanalytics.com",
    employee_count: 620,
    annual_revenue: "$92M",
    past_award_count: 14,
    past_award_value: "$175M",
    is_prime: true,
    teaming_fit_score: 82,
    contact_name: "James Whitfield",
    contact_email: "j.whitfield@summitanalytics.com",
    contact_phone: "(571) 555-0816",
    tags: ["New Contact"],
    created_at: "2025-01-05T11:00:00Z",
  },
  {
    id: "c5",
    name: "Vanguard Mission Systems",
    cage_code: "7T3R5",
    duns: "492163087",
    naics_codes: ["541330", "541511", "541512"],
    capabilities: [
      "Systems Engineering",
      "IT Modernization",
      "Enterprise Architecture",
      "DevSecOps",
    ],
    agencies_worked_with: ["Air Force", "Navy", "DoD"],
    location: "Colorado Springs, CO",
    website: "https://vanguardmission.com",
    employee_count: 3100,
    annual_revenue: "$520M",
    past_award_count: 38,
    past_award_value: "$890M",
    is_prime: true,
    teaming_fit_score: 96,
    contact_name: "Karen Liang",
    contact_email: "k.liang@vanguardmission.com",
    contact_phone: "(719) 555-0527",
    tags: ["Active Partner", "Top Performer", "Strategic"],
    created_at: "2024-05-30T08:45:00Z",
  },
  {
    id: "c6",
    name: "Clearpath Consulting Group",
    cage_code: "9D2M7",
    duns: "518374926",
    naics_codes: ["541611", "541613"],
    capabilities: [
      "Strategic Planning",
      "Change Management",
      "Performance Optimization",
      "Federal HR Consulting",
    ],
    agencies_worked_with: ["VA", "HHS", "USDA"],
    location: "Washington, DC",
    website: "https://clearpathconsulting.com",
    employee_count: 480,
    annual_revenue: "$68M",
    past_award_count: 11,
    past_award_value: "$95M",
    is_prime: true,
    teaming_fit_score: 73,
    contact_name: "Patricia Nguyen",
    contact_email: "p.nguyen@clearpathcg.com",
    contact_phone: "(202) 555-0683",
    tags: ["New Contact"],
    created_at: "2025-02-18T16:20:00Z",
  },
  {
    id: "c7",
    name: "Ironclad Infrastructure",
    cage_code: "4F9H3",
    duns: "631582047",
    naics_codes: ["238220", "541330", "561210"],
    capabilities: [
      "Facility Construction",
      "Critical Infrastructure",
      "HVAC & Electrical Systems",
      "Environmental Remediation",
    ],
    agencies_worked_with: ["Army", "DOE", "GSA"],
    location: "Huntsville, AL",
    website: "https://ironcladinfra.com",
    employee_count: 2400,
    annual_revenue: "$415M",
    past_award_count: 29,
    past_award_value: "$720M",
    is_prime: true,
    teaming_fit_score: 68,
    contact_name: "Robert Caldwell",
    contact_email: "r.caldwell@ironcladinfra.com",
    contact_phone: "(256) 555-0291",
    tags: ["Active Partner"],
    created_at: "2024-09-12T13:00:00Z",
  },
  {
    id: "c8",
    name: "Catalyst Federal",
    cage_code: "1G5N6",
    duns: "749203618",
    naics_codes: ["541511", "541519", "541611"],
    capabilities: [
      "Cloud Migration",
      "Agile Transformation",
      "Digital Services",
      "User Experience Design",
    ],
    agencies_worked_with: ["GSA", "VA", "DHS"],
    location: "McLean, VA",
    website: "https://catalystfederal.com",
    employee_count: 870,
    annual_revenue: "$128M",
    past_award_count: 21,
    past_award_value: "$310M",
    is_prime: true,
    teaming_fit_score: 89,
    contact_name: "Steven Park",
    contact_email: "s.park@catalystfederal.com",
    contact_phone: "(703) 555-0459",
    tags: ["Active Partner", "Preferred Vendor"],
    created_at: "2024-10-03T10:30:00Z",
  },
  {
    id: "c9",
    name: "Blueline Technologies",
    cage_code: "6W8Q4",
    duns: "856091372",
    naics_codes: ["541512", "541519", "561612"],
    capabilities: [
      "Network Engineering",
      "Telecommunications",
      "Physical Security Systems",
      "SCIF Construction",
    ],
    agencies_worked_with: ["DoD", "DHS", "Navy"],
    location: "Annapolis Junction, MD",
    website: "https://bluelinetech.com",
    employee_count: 1350,
    annual_revenue: "$210M",
    past_award_count: 24,
    past_award_value: "$380M",
    is_prime: true,
    teaming_fit_score: 78,
    contact_name: "Christine Morales",
    contact_email: "c.morales@bluelinetech.com",
    contact_phone: "(443) 555-0714",
    tags: ["Preferred Vendor"],
    created_at: "2024-11-21T09:00:00Z",
  },
  {
    id: "c10",
    name: "Pinnacle Logistics Solutions",
    cage_code: "0A3V2",
    duns: "962714083",
    naics_codes: ["561210", "541614", "541690"],
    capabilities: [
      "Supply Chain Management",
      "Warehousing & Distribution",
      "Fleet Management",
      "Logistics IT Systems",
    ],
    agencies_worked_with: ["Army", "USDA", "DHS"],
    location: "Tampa, FL",
    website: "https://pinnaclelogistics.com",
    employee_count: 1600,
    annual_revenue: "$275M",
    past_award_count: 18,
    past_award_value: "$410M",
    is_prime: true,
    teaming_fit_score: 65,
    contact_name: "Andrew Reeves",
    contact_email: "a.reeves@pinnaclelogistics.com",
    contact_phone: "(813) 555-0938",
    tags: ["New Contact"],
    created_at: "2025-03-01T14:00:00Z",
  },
  {
    id: "c11",
    name: "Trident Security Group",
    cage_code: "5B1X9",
    duns: "104835267",
    naics_codes: ["561612", "541512", "541519"],
    capabilities: [
      "Personnel Security",
      "Background Investigations",
      "Physical Security",
      "Insider Threat Programs",
    ],
    agencies_worked_with: ["DoD", "DHS", "DOE"],
    location: "Chantilly, VA",
    website: "https://tridentsecuritygroup.com",
    employee_count: 2800,
    annual_revenue: "$390M",
    past_award_count: 33,
    past_award_value: "$650M",
    is_prime: true,
    teaming_fit_score: 84,
    contact_name: "Nathan Voss",
    contact_email: "n.voss@tridentsecurity.com",
    contact_phone: "(571) 555-1023",
    tags: ["Active Partner", "Top Performer"],
    created_at: "2024-08-28T11:45:00Z",
  },
  {
    id: "c12",
    name: "Atlas Digital Services",
    cage_code: "7E4Z6",
    duns: "213946750",
    naics_codes: ["541511", "541519", "541330"],
    capabilities: [
      "Application Development",
      "API Integration",
      "Low-Code Platforms",
      "Robotic Process Automation",
    ],
    agencies_worked_with: ["GSA", "HHS", "VA"],
    location: "Austin, TX",
    website: "https://atlasdigitalservices.com",
    employee_count: 540,
    annual_revenue: "$78M",
    past_award_count: 9,
    past_award_value: "$112M",
    is_prime: true,
    teaming_fit_score: 76,
    contact_name: "Lisa Brennan",
    contact_email: "l.brennan@atlasdigital.com",
    contact_phone: "(512) 555-0467",
    tags: ["New Contact"],
    created_at: "2025-02-10T15:30:00Z",
  },
];

// ---------------------------------------------------------------------------
// Opportunities
// ---------------------------------------------------------------------------

export const opportunities: Opportunity[] = [
  {
    id: "o1",
    title: "Enterprise Cloud Migration Services",
    solicitation_number: "W911NF-24-R-0187",
    agency: "Army",
    sub_agency: "Army Contracting Command",
    description:
      "Full-scale migration of legacy on-premises systems to an AWS GovCloud environment, including application refactoring, data migration, security authorization, and continuous integration/continuous deployment pipeline implementation for 35+ mission-critical applications.",
    naics_code: "541511",
    set_aside: "Small Business",
    contract_type: "FFP",
    estimated_value: "$12.5M",
    place_of_performance: "Fort Belvoir, VA",
    posted_date: "2026-03-15T00:00:00Z",
    due_date: "2026-04-30T17:00:00Z",
    status: "bidding",
    pipeline_stage: "teaming",
    attachments: ["RFP_W911NF-24-R-0187.pdf", "Attachment_J_PWS.pdf"],
    url: "https://sam.gov/opp/abc123",
    created_at: "2026-03-15T08:00:00Z",
  },
  {
    id: "o2",
    title: "Cybersecurity Operations Center Support",
    solicitation_number: "FA8773-26-R-0042",
    agency: "Air Force",
    sub_agency: "Air Force Life Cycle Management Center",
    description:
      "Provide 24/7 cybersecurity operations center staffing, threat monitoring, incident response, vulnerability management, and security information and event management support for Air Force enterprise networks across CONUS installations.",
    naics_code: "541512",
    set_aside: "None",
    contract_type: "T&M",
    estimated_value: "$45M",
    place_of_performance: "San Antonio, TX",
    posted_date: "2026-03-01T00:00:00Z",
    due_date: "2026-05-15T14:00:00Z",
    status: "reviewing",
    pipeline_stage: "qualified",
    attachments: ["RFP_FA8773-26-R-0042.pdf"],
    url: "https://sam.gov/opp/def456",
    created_at: "2026-03-01T12:00:00Z",
  },
  {
    id: "o3",
    title: "Data Analytics Platform Development",
    solicitation_number: "W56HZV-26-R-0319",
    agency: "DoD",
    sub_agency: "Defense Information Systems Agency",
    description:
      "Design, develop, and deploy an enterprise data analytics platform leveraging modern big data technologies, machine learning models, and interactive dashboards to support decision-making across combatant commands.",
    naics_code: "541519",
    set_aside: "Small Business",
    contract_type: "CPFF",
    estimated_value: "$28M",
    place_of_performance: "Fort Meade, MD",
    posted_date: "2026-03-10T00:00:00Z",
    due_date: "2026-05-01T17:00:00Z",
    status: "bidding",
    pipeline_stage: "reaching_out",
    attachments: ["RFP_W56HZV-26-R-0319.pdf", "Data_Requirements.pdf"],
    url: "https://sam.gov/opp/ghi789",
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "o4",
    title: "IT Modernization and Infrastructure Upgrade",
    solicitation_number: "70RCSA26R00000045",
    agency: "GSA",
    sub_agency: "Federal Acquisition Service",
    description:
      "Modernize legacy IT infrastructure including server consolidation, network refresh, endpoint migration to Windows 11, and implementation of zero trust architecture across 12 regional GSA offices nationwide.",
    naics_code: "541511",
    set_aside: "8(a)",
    contract_type: "FFP",
    estimated_value: "$8.2M",
    place_of_performance: "Washington, DC",
    posted_date: "2026-02-28T00:00:00Z",
    due_date: "2026-04-18T12:00:00Z",
    status: "partnered",
    pipeline_stage: "submitted",
    attachments: ["RFP_70RCSA26R00000045.pdf", "SOW_Appendix_A.pdf"],
    url: "https://sam.gov/opp/jkl012",
    created_at: "2026-02-28T09:00:00Z",
  },
  {
    id: "o5",
    title: "Veterans Benefits Management System Enhancement",
    solicitation_number: "36C10X26R0081",
    agency: "VA",
    sub_agency: "Office of Information and Technology",
    description:
      "Enhance and maintain the Veterans Benefits Management System including new claims processing modules, workflow automation, reporting capabilities, and integration with external verification databases.",
    naics_code: "541511",
    set_aside: "SDVOSB",
    contract_type: "IDIQ",
    estimated_value: "$18.5M",
    place_of_performance: "Austin, TX",
    posted_date: "2026-03-20T00:00:00Z",
    due_date: "2026-05-20T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "new",
    attachments: ["RFP_36C10X26R0081.pdf"],
    url: "https://sam.gov/opp/mno345",
    created_at: "2026-03-20T14:00:00Z",
  },
  {
    id: "o6",
    title: "Physical Security and Access Control Systems",
    solicitation_number: "70Z04026R000012",
    agency: "DHS",
    sub_agency: "Customs and Border Protection",
    description:
      "Procure, install, and maintain integrated physical security and access control systems at 28 points of entry along the southern border, including biometric readers, surveillance cameras, and central monitoring stations.",
    naics_code: "561612",
    set_aside: "None",
    contract_type: "FFP",
    estimated_value: "$62M",
    place_of_performance: "El Paso, TX",
    posted_date: "2026-03-05T00:00:00Z",
    due_date: "2026-05-30T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "qualified",
    attachments: ["RFP_70Z04026R000012.pdf", "Technical_Specs.pdf"],
    url: "https://sam.gov/opp/pqr678",
    created_at: "2026-03-05T08:00:00Z",
  },
  {
    id: "o7",
    title: "Agile Software Development Services",
    solicitation_number: "75FCMC26R0039",
    agency: "HHS",
    sub_agency: "Centers for Medicare & Medicaid Services",
    description:
      "Provide agile software development teams to build and maintain healthcare data exchange platforms, provider enrollment systems, and beneficiary-facing web applications using modern frameworks and cloud-native technologies.",
    naics_code: "541511",
    set_aside: "Small Business",
    contract_type: "T&M",
    estimated_value: "$22M",
    place_of_performance: "Baltimore, MD",
    posted_date: "2026-03-18T00:00:00Z",
    due_date: "2026-05-08T17:00:00Z",
    status: "bidding",
    pipeline_stage: "teaming",
    attachments: ["RFP_75FCMC26R0039.pdf", "Agile_Methodology_Guide.pdf"],
    url: "https://sam.gov/opp/stu901",
    created_at: "2026-03-18T11:00:00Z",
  },
  {
    id: "o8",
    title: "Facility Maintenance and Repair Services",
    solicitation_number: "W912DY-26-R-0055",
    agency: "Army",
    sub_agency: "Army Corps of Engineers",
    description:
      "Provide comprehensive facility maintenance, repair, and minor construction services for military installations across the southeastern United States, including HVAC, electrical, plumbing, and structural work.",
    naics_code: "238220",
    set_aside: "HUBZone",
    contract_type: "IDIQ",
    estimated_value: "$35M",
    place_of_performance: "Fort Moore, GA",
    posted_date: "2026-02-20T00:00:00Z",
    due_date: "2026-04-15T14:00:00Z",
    status: "submitted",
    pipeline_stage: "submitted",
    attachments: ["RFP_W912DY-26-R-0055.pdf", "CLIN_Structure.pdf"],
    url: "https://sam.gov/opp/vwx234",
    created_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "o9",
    title: "Network Infrastructure Modernization",
    solicitation_number: "N00024-26-R-0128",
    agency: "Navy",
    sub_agency: "Naval Information Warfare Systems Command",
    description:
      "Upgrade and modernize network infrastructure across Navy shore installations, including fiber optic backbone installation, switch and router replacement, wireless network expansion, and network management tools deployment.",
    naics_code: "541512",
    set_aside: "Small Business",
    contract_type: "FFP",
    estimated_value: "$15.8M",
    place_of_performance: "San Diego, CA",
    posted_date: "2026-03-25T00:00:00Z",
    due_date: "2026-05-25T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "new",
    attachments: ["RFP_N00024-26-R-0128.pdf"],
    url: "https://sam.gov/opp/yza567",
    created_at: "2026-03-25T09:00:00Z",
  },
  {
    id: "o10",
    title: "Supply Chain Management System",
    solicitation_number: "AG-3A94-S-26-0017",
    agency: "USDA",
    sub_agency: "Agricultural Marketing Service",
    description:
      "Develop and deploy a comprehensive supply chain management system to track agricultural commodities from procurement through distribution, including real-time inventory, shipment tracking, and predictive analytics for demand forecasting.",
    naics_code: "541519",
    set_aside: "Small Business",
    contract_type: "FFP",
    estimated_value: "$4.8M",
    place_of_performance: "Kansas City, MO",
    posted_date: "2026-03-12T00:00:00Z",
    due_date: "2026-04-28T17:00:00Z",
    status: "bidding",
    pipeline_stage: "reaching_out",
    attachments: ["RFP_AG-3A94-S-26-0017.pdf"],
    url: "https://sam.gov/opp/bcd890",
    created_at: "2026-03-12T13:00:00Z",
  },
  {
    id: "o11",
    title: "Insider Threat Program Support",
    solicitation_number: "HQ0034-26-R-0076",
    agency: "DoD",
    sub_agency: "Defense Counterintelligence and Security Agency",
    description:
      "Provide program management, technical support, and training for the Department of Defense insider threat program, including user activity monitoring, behavioral analytics, and insider threat hub operations across combatant commands.",
    naics_code: "561612",
    set_aside: "None",
    contract_type: "CPFF",
    estimated_value: "$19.3M",
    place_of_performance: "Quantico, VA",
    posted_date: "2026-03-08T00:00:00Z",
    due_date: "2026-05-10T17:00:00Z",
    status: "bidding",
    pipeline_stage: "teaming",
    attachments: ["RFP_HQ0034-26-R-0076.pdf", "CDRL_List.pdf"],
    url: "https://sam.gov/opp/efg123",
    created_at: "2026-03-08T15:00:00Z",
  },
  {
    id: "o12",
    title: "Healthcare IT Systems Integration",
    solicitation_number: "36C10X26R0104",
    agency: "VA",
    sub_agency: "Veterans Health Administration",
    description:
      "Integrate electronic health record systems with third-party clinical applications, laboratory information systems, and pharmacy management tools to ensure seamless data flow across VA medical centers nationwide.",
    naics_code: "541511",
    set_aside: "SDVOSB",
    contract_type: "T&M",
    estimated_value: "$9.7M",
    place_of_performance: "Washington, DC",
    posted_date: "2026-03-22T00:00:00Z",
    due_date: "2026-05-22T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "new",
    attachments: ["RFP_36C10X26R0104.pdf"],
    url: "https://sam.gov/opp/hij456",
    created_at: "2026-03-22T10:00:00Z",
  },
  {
    id: "o13",
    title: "Energy Management and Sustainability Services",
    solicitation_number: "DE-SOL-0015892",
    agency: "DOE",
    sub_agency: "Office of Energy Efficiency",
    description:
      "Provide energy auditing, sustainability consulting, renewable energy system design, and energy management information system implementation across DOE laboratory and office facilities in support of federal sustainability goals.",
    naics_code: "541690",
    set_aside: "Small Business",
    contract_type: "FFP",
    estimated_value: "$6.1M",
    place_of_performance: "Oak Ridge, TN",
    posted_date: "2026-03-28T00:00:00Z",
    due_date: "2026-06-01T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "new",
    attachments: ["RFP_DE-SOL-0015892.pdf"],
    url: "https://sam.gov/opp/klm789",
    created_at: "2026-03-28T12:00:00Z",
  },
  {
    id: "o14",
    title: "DevSecOps Platform and CI/CD Pipeline Services",
    solicitation_number: "FA8726-26-R-0091",
    agency: "Air Force",
    sub_agency: "Air Force Research Laboratory",
    description:
      "Establish and operate a DevSecOps platform providing automated security testing, continuous integration and deployment pipelines, container orchestration, and infrastructure-as-code capabilities for mission application development teams.",
    naics_code: "541511",
    set_aside: "Small Business",
    contract_type: "FFP",
    estimated_value: "$14.2M",
    place_of_performance: "Wright-Patterson AFB, OH",
    posted_date: "2026-03-30T00:00:00Z",
    due_date: "2026-06-05T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "qualified",
    attachments: ["RFP_FA8726-26-R-0091.pdf", "Tech_Eval_Criteria.pdf"],
    url: "https://sam.gov/opp/nop012",
    created_at: "2026-03-30T08:00:00Z",
  },
  {
    id: "o15",
    title: "Workforce Management Consulting",
    solicitation_number: "VA101-26-R-0208",
    agency: "VA",
    sub_agency: "Office of Human Resources",
    description:
      "Provide workforce planning, talent acquisition strategy, employee engagement consulting, and HR technology implementation support to modernize the VA human capital management framework and reduce time-to-hire across all service lines.",
    naics_code: "541611",
    set_aside: "WOSB",
    contract_type: "T&M",
    estimated_value: "$3.9M",
    place_of_performance: "Washington, DC",
    posted_date: "2026-04-01T00:00:00Z",
    due_date: "2026-05-30T17:00:00Z",
    status: "reviewing",
    pipeline_stage: "new",
    attachments: ["RFP_VA101-26-R-0208.pdf"],
    url: "https://sam.gov/opp/qrs345",
    created_at: "2026-04-01T09:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Past Awards
// ---------------------------------------------------------------------------

export const pastAwards: PastAward[] = [
  {
    id: "pa1",
    contractor_id: "c1",
    title: "Endpoint Detection and Response Deployment",
    agency: "DoD",
    value: "$8.4M",
    award_date: "2024-11-15T00:00:00Z",
    naics_code: "541512",
    description:
      "Deployed enterprise EDR solution across 120,000 endpoints with real-time threat detection and automated response playbooks.",
  },
  {
    id: "pa2",
    contractor_id: "c1",
    title: "Zero Trust Network Architecture Implementation",
    agency: "DHS",
    value: "$14.2M",
    award_date: "2024-06-22T00:00:00Z",
    naics_code: "541512",
    description:
      "Designed and implemented zero trust architecture including micro-segmentation, identity-aware proxy, and continuous authentication for critical infrastructure networks.",
  },
  {
    id: "pa3",
    contractor_id: "c2",
    title: "Organizational Transformation Initiative",
    agency: "VA",
    value: "$5.8M",
    award_date: "2025-01-10T00:00:00Z",
    naics_code: "541611",
    description:
      "Led enterprise-wide organizational restructuring to improve service delivery, including process reengineering and change management for 15,000+ employees.",
  },
  {
    id: "pa4",
    contractor_id: "c3",
    title: "Red Team Assessment Program",
    agency: "Air Force",
    value: "$3.2M",
    award_date: "2025-03-05T00:00:00Z",
    naics_code: "541512",
    description:
      "Conducted adversarial red team assessments across 22 Air Force installations, identifying critical vulnerabilities and providing remediation roadmaps.",
  },
  {
    id: "pa5",
    contractor_id: "c4",
    title: "Predictive Maintenance Analytics Platform",
    agency: "Army",
    value: "$6.7M",
    award_date: "2024-09-18T00:00:00Z",
    naics_code: "541519",
    description:
      "Developed machine learning models for predictive maintenance of ground vehicle fleets, reducing unplanned downtime by 38%.",
  },
  {
    id: "pa6",
    contractor_id: "c5",
    title: "Enterprise Architecture Modernization",
    agency: "Air Force",
    value: "$22.5M",
    award_date: "2024-04-30T00:00:00Z",
    naics_code: "541330",
    description:
      "Redesigned enterprise architecture to support cloud-first strategy, including migration roadmap, target state architecture, and governance framework.",
  },
  {
    id: "pa7",
    contractor_id: "c5",
    title: "DevSecOps Transformation",
    agency: "Navy",
    value: "$11.3M",
    award_date: "2025-02-14T00:00:00Z",
    naics_code: "541511",
    description:
      "Implemented DevSecOps pipeline and platform for 40+ application development teams, reducing deployment frequency from quarterly to daily.",
  },
  {
    id: "pa8",
    contractor_id: "c6",
    title: "Federal Workforce Planning Initiative",
    agency: "HHS",
    value: "$2.9M",
    award_date: "2024-12-01T00:00:00Z",
    naics_code: "541611",
    description:
      "Developed comprehensive workforce planning framework including skills gap analysis, succession planning, and recruitment strategy for 8 HHS operating divisions.",
  },
  {
    id: "pa9",
    contractor_id: "c7",
    title: "Barracks Renovation Program",
    agency: "Army",
    value: "$47.2M",
    award_date: "2024-07-20T00:00:00Z",
    naics_code: "238220",
    description:
      "Complete renovation of 14 barracks buildings including HVAC replacement, electrical upgrades, plumbing modernization, and ADA compliance modifications.",
  },
  {
    id: "pa10",
    contractor_id: "c7",
    title: "Data Center Power Infrastructure",
    agency: "DOE",
    value: "$18.6M",
    award_date: "2025-01-28T00:00:00Z",
    naics_code: "238220",
    description:
      "Designed and constructed redundant power distribution systems for Tier III data center facility, including UPS, generators, and switchgear.",
  },
  {
    id: "pa11",
    contractor_id: "c8",
    title: "Cloud-Native Application Platform",
    agency: "GSA",
    value: "$9.1M",
    award_date: "2024-10-12T00:00:00Z",
    naics_code: "541511",
    description:
      "Built and deployed a cloud-native application platform on AWS GovCloud using Kubernetes, enabling rapid application deployment across federal agencies.",
  },
  {
    id: "pa12",
    contractor_id: "c8",
    title: "Digital Services Modernization",
    agency: "VA",
    value: "$7.4M",
    award_date: "2025-03-15T00:00:00Z",
    naics_code: "541511",
    description:
      "Redesigned veteran-facing digital services portal with improved accessibility, mobile responsiveness, and integration with backend claims processing systems.",
  },
  {
    id: "pa13",
    contractor_id: "c9",
    title: "Classified Network Expansion",
    agency: "DoD",
    value: "$16.8M",
    award_date: "2024-08-05T00:00:00Z",
    naics_code: "541512",
    description:
      "Extended classified network infrastructure to 35 new locations with fiber optic installation, encryption devices, and secure switching equipment.",
  },
  {
    id: "pa14",
    contractor_id: "c10",
    title: "Global Logistics Tracking System",
    agency: "Army",
    value: "$12.3M",
    award_date: "2024-11-30T00:00:00Z",
    naics_code: "561210",
    description:
      "Developed real-time logistics tracking system for global supply chain operations with RFID integration, predictive delivery analytics, and dashboard reporting.",
  },
  {
    id: "pa15",
    contractor_id: "c11",
    title: "Insider Threat Detection System",
    agency: "DoD",
    value: "$8.9M",
    award_date: "2025-02-20T00:00:00Z",
    naics_code: "561612",
    description:
      "Implemented user activity monitoring and behavioral analytics platform across DoD enterprise, processing 2M+ daily events with machine learning threat scoring.",
  },
  {
    id: "pa16",
    contractor_id: "c11",
    title: "Personnel Security Clearance Processing",
    agency: "DHS",
    value: "$5.6M",
    award_date: "2024-05-10T00:00:00Z",
    naics_code: "561612",
    description:
      "Managed background investigation and adjudication support for 45,000 personnel security clearance cases annually with 99.2% on-time completion rate.",
  },
  {
    id: "pa17",
    contractor_id: "c12",
    title: "Benefits Portal Modernization",
    agency: "HHS",
    value: "$4.3M",
    award_date: "2024-09-25T00:00:00Z",
    naics_code: "541511",
    description:
      "Rebuilt legacy benefits portal using React and Node.js microservices architecture, improving page load times by 70% and reducing support tickets by 45%.",
  },
  {
    id: "pa18",
    contractor_id: "c3",
    title: "Cloud Security Assessment Program",
    agency: "DHS",
    value: "$4.8M",
    award_date: "2024-12-10T00:00:00Z",
    naics_code: "541512",
    description:
      "Performed comprehensive security assessments of 50+ cloud workloads across multiple CSPs, producing FedRAMP-aligned authorization packages.",
  },
  {
    id: "pa19",
    contractor_id: "c4",
    title: "Intelligence Data Fusion Platform",
    agency: "DoD",
    value: "$15.1M",
    award_date: "2025-01-18T00:00:00Z",
    naics_code: "541519",
    description:
      "Built multi-source data fusion platform ingesting structured and unstructured intelligence data, with NLP-based entity extraction and graph-based relationship analysis.",
  },
  {
    id: "pa20",
    contractor_id: "c2",
    title: "Acquisition Process Improvement",
    agency: "GSA",
    value: "$3.4M",
    award_date: "2025-03-22T00:00:00Z",
    naics_code: "541611",
    description:
      "Streamlined federal acquisition processes reducing average procurement cycle time by 30% through process mapping, automation recommendations, and staff training.",
  },
];

// ---------------------------------------------------------------------------
// Saved Searches
// ---------------------------------------------------------------------------

export const savedSearches: SavedSearch[] = [
  {
    id: "ss1",
    user_id: "u1",
    name: "Cyber Opps — Small Business Set-Aside",
    filters: {
      naics_codes: ["541512", "541519"],
      set_aside: "Small Business",
      agencies: ["DoD", "DHS", "Air Force"],
    },
    alert_enabled: true,
    alert_frequency: "daily",
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "ss2",
    user_id: "u1",
    name: "VA IT Modernization",
    filters: {
      naics_codes: ["541511"],
      agencies: ["VA"],
      min_value: "$5M",
    },
    alert_enabled: true,
    alert_frequency: "instant",
    created_at: "2026-02-03T14:00:00Z",
  },
  {
    id: "ss3",
    user_id: "u1",
    name: "Army Infrastructure Projects",
    filters: {
      naics_codes: ["238220", "541330"],
      agencies: ["Army"],
      set_aside: "HUBZone",
    },
    alert_enabled: false,
    alert_frequency: "weekly",
    created_at: "2026-02-20T09:00:00Z",
  },
  {
    id: "ss4",
    user_id: "u1",
    name: "SDVOSB Opportunities Over $10M",
    filters: {
      set_aside: "SDVOSB",
      min_value: "$10M",
    },
    alert_enabled: true,
    alert_frequency: "daily",
    created_at: "2026-03-01T11:30:00Z",
  },
  {
    id: "ss5",
    user_id: "u1",
    name: "Management Consulting — HHS & GSA",
    filters: {
      naics_codes: ["541611", "541613"],
      agencies: ["HHS", "GSA"],
    },
    alert_enabled: true,
    alert_frequency: "weekly",
    created_at: "2026-03-10T16:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Dashboard Metrics
// ---------------------------------------------------------------------------

export const dashboardMetrics: DashboardMetrics = {
  total_opportunities: 247,
  tracked_opportunities: 15,
  saved_primes: 12,
  upcoming_deadlines: 6,
  pipeline_counts: {
    new: 4,
    qualified: 3,
    reaching_out: 2,
    teaming: 3,
    submitted: 3,
  },
  opportunities_by_agency: [
    { agency: "DoD", count: 58 },
    { agency: "Army", count: 42 },
    { agency: "Air Force", count: 35 },
    { agency: "Navy", count: 28 },
    { agency: "DHS", count: 24 },
    { agency: "VA", count: 22 },
    { agency: "GSA", count: 18 },
    { agency: "HHS", count: 12 },
    { agency: "DOE", count: 5 },
    { agency: "USDA", count: 3 },
  ],
  opportunities_by_month: [
    { month: "Nov 2025", count: 18 },
    { month: "Dec 2025", count: 22 },
    { month: "Jan 2026", count: 31 },
    { month: "Feb 2026", count: 28 },
    { month: "Mar 2026", count: 45 },
    { month: "Apr 2026", count: 37 },
  ],
};

// ---------------------------------------------------------------------------
// Notes
// ---------------------------------------------------------------------------

export const notes: Note[] = [
  {
    id: "n1",
    user_id: "u1",
    entity_type: "contractor",
    entity_id: "c1",
    content:
      "Spoke with Rebecca Thornton on 3/15 — Northbridge is actively looking for small business partners on their DISA BPA. They need cloud security expertise and are open to mentor-protege arrangements. Follow up next week with capability brief.",
    created_at: "2026-03-15T16:30:00Z",
  },
  {
    id: "n2",
    user_id: "u1",
    entity_type: "opportunity",
    entity_id: "o1",
    content:
      "Strong fit for our cloud migration capabilities. Northbridge (c1) and Catalyst Federal (c8) both expressed interest in teaming. Need to finalize teaming agreement by 4/10 to meet proposal timeline.",
    created_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "n3",
    user_id: "u1",
    entity_type: "opportunity",
    entity_id: "o2",
    content:
      "This is a large unrestricted opportunity — will need a prime with existing AFNET access. Apex Cyber Group has the relationships and clearances. Sent intro email to Maria Santos on 3/22.",
    created_at: "2026-03-22T14:15:00Z",
  },
  {
    id: "n4",
    user_id: "u1",
    entity_type: "contractor",
    entity_id: "c5",
    content:
      "Vanguard is our strongest teaming partner. Karen Liang confirmed they are bidding on the AFRL DevSecOps opportunity (o14) and want us on the team for CI/CD pipeline work. Excellent past performance together.",
    created_at: "2026-03-28T11:00:00Z",
  },
  {
    id: "n5",
    user_id: "u1",
    entity_type: "opportunity",
    entity_id: "o7",
    content:
      "CMS agile development is right in our wheelhouse. Atlas Digital (c12) has the CMS domain knowledge and existing BPA access. Set up a call for 4/5 to discuss teaming approach.",
    created_at: "2026-03-30T09:45:00Z",
  },
  {
    id: "n6",
    user_id: "u1",
    entity_type: "contractor",
    entity_id: "c8",
    content:
      "Steven Park mentioned Catalyst Federal is pursuing the GSA IT Modernization opportunity (o4) as prime. They submitted their proposal on 3/25. Should hear back by end of April.",
    created_at: "2026-03-25T15:20:00Z",
  },
  {
    id: "n7",
    user_id: "u1",
    entity_type: "opportunity",
    entity_id: "o11",
    content:
      "Insider threat is a growing area. Trident Security Group (c11) has deep experience here and won a similar contract last year. They are interested in having us provide the analytics and ML components.",
    created_at: "2026-04-01T10:30:00Z",
  },
  {
    id: "n8",
    user_id: "u1",
    entity_type: "contractor",
    entity_id: "c3",
    content:
      "Apex Cyber just won a $4.8M cloud security assessment contract with DHS. Their SOC capabilities are top-tier. Maria Santos is our main POC — very responsive and collaborative.",
    created_at: "2026-04-02T13:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Helper Functions
// ---------------------------------------------------------------------------

export function getContractorById(
  id: string
): ContractorProfile | undefined {
  return contractors.find((c) => c.id === id);
}

export function getOpportunityById(id: string): Opportunity | undefined {
  return opportunities.find((o) => o.id === id);
}

export function getContractorOpportunities(
  contractorId: string
): Opportunity[] {
  const contractor = getContractorById(contractorId);
  if (!contractor) return [];
  return opportunities.filter((o) =>
    contractor.naics_codes.includes(o.naics_code)
  );
}

export function getContractorPastAwards(contractorId: string): PastAward[] {
  return pastAwards.filter((a) => a.contractor_id === contractorId);
}

export function getRecommendedPrimes(
  opportunityId: string
): ContractorProfile[] {
  const opportunity = getOpportunityById(opportunityId);
  if (!opportunity) return [];
  return contractors
    .filter((c) => c.naics_codes.includes(opportunity.naics_code))
    .sort((a, b) => (b.teaming_fit_score ?? 0) - (a.teaming_fit_score ?? 0));
}
